### ISSUE TITLE
panic: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by gr4y** [gr4y/fitbit-graphite#2]
I will just leave this here for later inspection:

> panic: invalid character '<' looking for beginning of value
> 
> goroutine 1 [running]:
> panic(0x31cba0, 0x10973110)
>         /usr/lib/go/src/runtime/panic.go:481 +0x330
> main.main.func1(0x1077ea20)
>         /home/sascha/gocode/src/github.com/gr4y/fitbit-graphite/fitbit-graphite.go:104 +0x9f8
> github.com/codegangsta/cli.(*App).Run(0x1077a140, 0x1076c120, 0x3, 0x4, 0x0, 0x0)
>         /home/sascha/gocode/src/github.com/codegangsta/cli/app.go:180 +0xde4
> main.main()
>         /home/sascha/gocode/src/github.com/gr4y/fitbit-graphite/fitbit-graphite.go:123 +0x444

**Comment by gr4y** [comment]
Well... It's just a weird way how FitBit just handles this, but... 
https://community.fitbit.com/t5/Web-API/504-Error-Code-for-activityCalories/m-p/1579598/highlight/true#M6393

**Comment by gr4y** [comment]
```
#### DEBUG Output Begin ####
Request URL: https://api.fitbit.com/1/user/-/activities/activityCalories/date/today/1y.json


### HTTP Request ###
Request: &{Method:GET URL:https://api.fitbit.com/1/user/-/activities/activityCalories/date/today/1y.json Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Authorization:[Bearer 123.12fds.312]] Body:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:api.fitbit.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil>}

### HTTP Response
Response Object: &{Status:504 Gateway Timeout StatusCode:504 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Server:[cloudflare-nginx] Cf-Ray:[3029f9e368d0268a-FRA] Date:[Wed, 16 Nov 2016 09:39:40 GMT] Content-Type:[text/html; charset=UTF-8] Expires:[Thu, 01 Jan 1970 00:00:01 GMT] Cache-Control:[no-store, no-cache, must-revalidate, post-check=0, pre-check=0] Pragma:[no-cache] X-Frame-Options:[SAMEORIGIN]] Body:0x1094a060 ContentLength:-1 TransferEncoding:[] Close:false Trailer:map[] Request:0x108da230 TLS:0x1094f920}
Response Body: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<meta http-equiv="set-cookie" content="cf_use_ob=0; expires=Wed, 16-Nov-16 09:40:10 GMT; path=/">


<title>api.fitbit.com | 504: Gateway time-out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

</head>
<body>
<div id="cf-wrapper">



    <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-error-overview">
            <h1>
              <span class="cf-error-type" data-translate="error">Error</span>
              <span class="cf-error-code">504</span>
              <small class="heading-ray-id">Ray ID: 3029f9e368d0268a &bull; 2016-11-16 09:39:40 UTC</small>
            </h1>
            <h2 class="cf-subheadline" data-translate="error_desc">Gateway time-out</h2>
        </div><!-- /.error-overview -->

        <div class="cf-section cf-highlight cf-status-display">
            <div class="cf-wrapper">
                <div class="cf-columns cols-3">

<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-browser"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc" data-translate="browser_desc">You</span>
  <h3 class="cf-status-name" data-translate="browser_label">Browser</h3>
  <span class="cf-status-label" data-translate="browser_status_label">Working</span>
</div>

<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-cloud"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc" data-translate="cloud_desc">Frankfurt</span>
  <h3 class="cf-status-name" data-translate="cloud_label">CloudFlare</h3>
  <span class="cf-status-label" data-translate="cloud_status_label">Working</span>
</div>

<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-server"></i>
    <i class="cf-icon-status cf-icon-error"></i>
  </div>
  <span class="cf-status-desc" data-translate="server_desc">api.fitbit.com</span>
  <h3 class="cf-status-name" data-translate="server_label">Host</h3>
  <span class="cf-status-label" data-translate="server_status_label">Error</span>
</div>

                </div>
            </div>
        </div><!-- /.status-display -->

        <div class="cf-section cf-wrapper">
            <div class="cf-columns two">
                <div class="cf-column">
                    <h2 data-translate="what_happened">What happened?</h2>
                    <p>The web server reported a gateway time-out error.</p>
                </div>

                <div class="cf-column">
                    <h2 data-translate="what_can_i_do">What can I do?</h2>
                    <p data-translate="try_again_in_a_few">Please try again in a few minutes.</p>
                </div>
            </div>
        </div><!-- /.section -->

        <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">CloudFlare Ray ID: <strong>3029f9e368d0268a</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 95.90.209.39</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">CloudFlare</a></span>

  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
</div><!-- /#cf-wrapper -->

#### DEBUG Output End ####
panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
panic(0x329290, 0x10942b70)
        /usr/lib/go/src/runtime/panic.go:481 +0x330
main.main.func1(0x10776140)
        /home/sascha/gocode/src/github.com/gr4y/fitbit-graphite/fitbit-graphite.go:104 +0x9f8
github.com/codegangsta/cli.HandleAction(0x2e9088, 0x406f20, 0x10776140, 0x0, 0x0)
        /home/sascha/gocode/src/github.com/codegangsta/cli/app.go:485 +0xa8
github.com/codegangsta/cli.(*App).Run(0x10758340, 0x10762160, 0x3, 0x4, 0x0, 0x0)
        /home/sascha/gocode/src/github.com/codegangsta/cli/app.go:254 +0x9ac
main.main()
        /home/sascha/gocode/src/github.com/gr4y/fitbit-graphite/fitbit-graphite.go:123 +0x3e4
```

This is still a thing. I guess.
